replicaCount: 1

image:
  repository: lekimtanloc/02-backend_spring-boot-rest-api
  tag: v1
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: dockerhub-secret

service:
  type: NodePort
  port: 8080
  nodePort: 30646   

ingress:
  enabled: true
  className: ""
  hosts:
    - host: lekimtanloc.dev.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

config:
  SPRING_PROFILES_ACTIVE: "prod"
  JAVA_OPTS: "-Xmx512m"

secret:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mariadb:3306/full-stack-ecommerce"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
