apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "02-backend-spring-boot-rest-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "02-backend-spring-boot-rest-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "02-backend-spring-boot-rest-api.name" . }}
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: {{ include "02-backend-spring-boot-rest-api.fullname" . }}-config
            - secretRef:
                name: {{ include "02-backend-spring-boot-rest-api.fullname" . }}-secret
