apiVersion: v1
kind: Service
metadata:
  name: {{ include "02-backend-spring-boot-rest-api.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort | default nil }}
  selector:
    app: {{ include "02-backend-spring-boot-rest-api.name" . }}
